using System;
using System.Collections.Generic;
using System.Linq;
using System.Text;
using System.Threading.Tasks;

namespace Nopioseev2
{
    /// <summary>
    /// Built In words
    /// </summary>
    internal class BuiltIn
    {
        /// <summary>
        /// The list of built-in words
        /// </summary>
        public static Dictionary<string, string> BuiltIns = new Dictionary<string, string>()
        {
            // Very epic english shortcuts
            { "it's ", " it is" },
            { "its ", " it is" },
            { "thats ", " that is" },
            { "that's ", " that is" },
            { "i'm ", " i am" },
            { "aren't ", " not" },
            { "im ", " i am" },
            { "don't ", " do not" },
            { "dont ", " do not" },
            { "wanna ", " want to" },
            { "you're ", " you are" },
            { "gotta ", " need to" },
            // Words that are easy or whatever you call them I am too stupid to know
            { "please ", "  ta mei play" },
            { "i want ", " paso" },
            { "what is ", " dimi" },
            { "did you ", " davelo" },
            { "am free ", " am outo" },
            { "such as ", " soga" },
            { "she is free ", " shi equ outo" },
            { "free ", " gracie" },
            // Misc
            { "you have ", " masteqe" },
            { "kidding ", " qavoe" },
            { "want ", " je" },
            { "are you ", " qi" },
            { "i first ", " solo" },
            { "first ", " beginn" },
            { "remove ", " da unis" },
            { "the ", " da" },
            { "right at ", " rach e" },
            { "of ", " qae" },
            { "to ", " y" },
            { "and ", " en" },
            { "a ", " a" },
            { "in ", " co" },
            { "is ", " equ" },
            { "it ", " cal" },
            { "you ", " un" },
            { "that ", " jet" },
            { "that is a ", " jet equ ze" },
            { "he ", " hi" },
            { "she ", " shi" },
            { "was ", " eror" },
            { "for ", " ta" },
            { "on ", " on" },
            { "with ", " imusing" },
            { "as ", " assoc" },
            { "i ", " mei" },
            { "are ", " q" },
            { "his ", " his" },
            { "her ", " shis" },
            { "they ", " jar" },
            { "be ", " had" },
            { "at ", " tocix" },
            { "one ", " zao" },
            { "have ", " ic" },
            { "this ", " zae" },
            { "from ", " freind" },
            { "or ", " que" },
            { "had ", " yeq" },
            { "by ", " err" },
            { "not ", " nouhva" },
            { "word ", " klas" },
            { "but ", " exe" },
            { "what ", " asqe" },
            { "some ", " tu" },
            { "we ", " qu" },
            { "can ", " sa" },
            { "out ", " nin" },
            { "other ", " oss" },
            { "were ", " user" },
            { "all ", " verwij" },
            { "there ", " tyhre" },
            { "when ", " whan" },
            { "up ", " diru" },
            { "use ", " gess" },
            { "your ", " yar" },
            { "how ", " toh" },
            { "said ", " talned" },
            { "talk ", " talne" },
            { "poop ", " buopu" },
            { "output ", " opu" },
            { "welcome ", " wyhere" },
            { "cool ", " yhas" },
            { "apple ", " appel" },
            { "water ", " holdon" },
            { "lava ", " lava" },
            { "easy ", " makli" },
            { "dance ", " dans" },
            { "dancing ", " dansing" },
            { "fire ", " fair" },
            { "delete ", " da unis" },
            { "removed ", " da unise" },
            { "removes ", " da unise" },
            { "deleted ", " da unise" },
            { "deletes ", " da unise" },
            { "nothing ", " unis" },
            { "name ", " nym" },
            { "tree ", " bot" },
            { "grass ", " grous" },
            { "house ", " hisj" },
            { "forgot ", " forged" },
            { "forget ", " forge" },
            { "sure ", " yos" },
            { "going ", " gutil" },
            { "if ", " wha" },
            { "yes ", " ja" },
            { "know ", " nó" },
            { "no ", " ne" },
            { "compare ", " samm" },
            { "two ", " tho" },
            { "three ", " grettho" },
            { "great ", " gret" },
            { "joke ", " qavo" },
            { "jokes ", " qeve" },
            { "joking ", " qave" },
            { "four ", " fortt" },
            { "five ", " faif" },
            { "six ", " syzz" },
            { "seven ", " savn" },
            { "eight ", " rofin" },
            { "nine ", " nei" },
            { "ten ", " thijn" },
            { "eleven ", " eddev" },
            { "hundred thousand ", " superthijn" },
            { "hundred ", " exthijn" },
            { "thousand ", " exexthijn" },
            { "million ", " milleon" },
            { "billion ", " billeon" },
            { "trillion ", " trilleon" },
            { "quadrillion ", " quadrilleon" },
            { "quintillion ", " quintilleon" },
            { "crazy ", " amaz" },
            { "hello ", " henlo" },
            { "heart ", " corzo" },
            { "home ", " hisj" },
            { "new ", " nieuw" },
            { "key ", " top" },
            { "board ", " bord" },
            { "keyboard ", " topbord" },
            { "universe ", " univars" },
            { "dog ", " dag" },
            { "cat ", " kat" },
            { "dogs ", " dage" },
            { "cats ", " kate" },
            { "hey ", " henlo" },
            { "maybe ", " mischen" },
            { "still ", " toc" },
            { "right ", " rach" },
            { "okay ", " ok" },
            { "cold ", " kuod" },
            { "hot ", " het" },
            { "warm ", " heet" },
            { "gold ", " geite" },
            { "huge ", " big" },
            { "monster ", " monstre" },
            { "quad ", " mik" },
            { "just ", " jaq" },
            { "about ", " gon" },
            { "version ", " versiy" },
            { "need ", " nee" },
            { "permission ", " permissie" },
            { "close ", " le disa" },
            { "continue ", " le goto" },
            { "cannot ", " sa nouhva" },
            { "valid ", " valide" },
            { "save ", " oplisn" },
            { "calculate ", " calcula" },
            { "calculator ", " calcular" },
            { "simple ", " simpel" },
            { "number ", " digi" },
            { "control ", " centre" },
            { "controller ", " centrell" },
            { "press ", " ola" },
            { "letter ", " latt" },
            { "letters ", " latts" },
            { "characters ", " chars" },
            { "tried ", " tryd" },
            { "look ", " mira" },
            { "question ", " pasas" },
            { "questions ", " pasase" },
            { "any ", " qe" },
            { "love ", " corzobe" },
            { "slow ", " calow" },
            { "fast ", " cahi" },
            { "quick ", " cahi" },
            { "sex ", " fakka" },
            { "today ", " vandahg" },
            { "too ", " ys" },
            { "rule ", " gahhr" },
            { "rules ", " gahhre" },
            { "stranger ", " string" },
            { "strangers ", " stringe" },
            { "never ", " novva" },
            { "give ", " gyvv" },
            { "bye ", " varwell" },
            { "goodbye ", " varwell" },
            { "been ", " bin" },
            { "around ", " ax" },
            { "full ", " maxi" },
            { "holiday ", " nicedahg" },
            { "day ", " dahg" },
            { "write ", " wrait" },
            { "writes ", " wraite" },
            { "doing ", " doon" },
            { "really ", " looto" },
            { "like ", " loo" },
            { "words ", " klasse" },
            { "idiot ", " idioot" },
            { "idiots ", " idioote" },
            { "language ", " taal" },
            { "languages ", " taale" },
            { "hate ", " haates" },
            { "hates ", " haatese" },
            { "without ", " zondre" },
            { "amount ", " sizo" },
            { "someone ", " tuian" },
            { "something ", " tuess" },
            { "ask ", " qesa" },
            { "asking ", " qesae" },
            { "which ", " welk" },
            { "used ", " gesse" },
            { "using ", " gessene" },
            { "longer ", " lengre" },
            { "invalid ", " incrate" },
            { "recoverable ", " regetabel" },
            { "unrecoverable ", " inregetabel" },
            { "protection ", " vededige" },
            { "protect ", " vededig" },
            { "unrecognized", " inrecognized" },
            { "must", " mus" },
            { "present ", " pressena" },
            { "system ", " systeem" },
            { "error ", " fatle" },
            { "fatal ", " fettele" },
            { "table ", " tabel" },
            { "tables ", " tabele" },
            { "my ", " ya" },
            { "feel ", " be" },
            { "feeling ", " ebe" },
            { "eat ", " eet" },
            { "eats ", " eete" },
            { "eating ", " eete" },
            { "baby ", " chel" },
            { "child ", " chella" },
            { "drink ", " eer" },
            { "drinks ", " eere" },
            { "drinking ", " eere" },
            { "cake ", " keek" },
            { "more ", " mer" },
            { "attempt ", " at" },
            { "file ", " exto" },
            { "folder ", " map" },
            { "directory ", " map" },
            { "specify ", " spec" },
            { "specified ", " spec" },
            { "specific ", " spece" },
            { "specifies ", " speca" },
            { "type ", " tik" },
            { "types ", " tike" },
            { "typing ", " tike" },
            { "text ", " tekst" },
            { "texting ", " tekste" },
            { "texted ", " tekste" },
            { "change ", " chas" },
            { "changing ", " chase" },
            { "changed ", " chase" },
            { "program ", " programme" },
            { "programming ", " program" },
            { "screen ", " scherm" },
            { "following ", " nekst" },
            { "follow ", " nek" },
            { "special ", " speciaalen" },
            { "default ", " normale" },
            { "setting ", " instan" },
            { "settings ", " instane" },
            { "now ", " nu" },
            { "current ", " now" },
            { "currently ", " nowe" },
            { "displays ", " monitere" },
            { "display ", " moniter" },
            { "because ", " omdat" },
            { "either ", " az" },
            { "missing ", " unfin" },
            { "tell ", " como" },
            { "gay ", " homo" },
            { "gays ", " homoe" },
            { "so ", " soy" },
            { "music ", " musiek" },
            { "ball ", " bal" },
            { "difficult ", " difficil" },
            { "difficulty ", " difficile" },
            { "night ", " yano" },
            { "tonight ", " noyano" },
            { "boy ", " nano" },
            { "girl ", " nani" },
            { "man ", " grano" },
            { "woman ", " grani" },
            { "dumb ", " domelement" },
            { "then ", " es" },
            { "buy ", " perche" },
            { "purchase ", " perche" },
            { "purchased ", " eperche" },
            { "bought ", " eperche" },
            { "master ", " mess" },
            { "teacher ", " teclar" },
            { "teachers ", " teclare" },
            { "toilet ", " toilette" },
            { "go ", " goto" },
            { "amazing ", " hanya" },
            { "amazed ", " hanyae" },
            { "boss ", " berfung" },
            { "bosses ", " berfunge" },
            { "thank un ", " berfussi" },
            { "thanks ", " berfussi" },
            { "imagination ", " imaginacíon" },
            { "translate ", " transacíon" },
            { "translated ", " transacíone" },
            { "game ", " spel" },
            { "games ", " spele" },
            { "gaming ", " spela" },
            { "abbreviation ", " simpelecíon" },
            { "abbreviations ", " simpelecíone" },
            { "animal ", " anymel" },
            { "animals ", " anymele" },
            { "cute ", " hox" },
            { "experience ", " pengelemen" },
            { "experiences ", " pengelemene" },
            { "experiencing ", " pengelemena" },
            { "command ", " komander" },
            { "commands ", " komandere" },
            { "commanding ", " komandera" },
            { "computer ", " computadoll" },
            { "computers ", " computadolle" },
            { "computing ", " computadolla" },
            { "normal ", " okal" },
            { "normally ", " okale" },
            { "certain ", " tu" },
            { "applications ", " appecíone" },
            { "application ", " appecíon" },
            { "apps ", " appe" },
            { "files ", " exto" },
            { "cooler ", " yhasa" },
            { "color ", " kolor" },
            { "colors ", " kolore" },
            { "black ", " zwart" },
            { "gray ", " greis" },
            { "white ", " whit" },
            { "purple ", " porpel" },
            { "green ", " groel" },
            { "lime ", " cimoen" },
            { "yellow ", " geel" },
            { "blue ", " bouw" },
            { "orange ", " sinas" },
            { "zero ", " null" },
            { "favorite ", " favoritto" },
            { "favorites ", " favorittoe" },
            { "start ", " beginne" },
            { "additional ", " additicíon" },
            { "task ", " tako" },
            { "tasks ", " takoe" },
            { "apples ", " appele" },
            { "easiest ", " makliest" },
            { "defaults ", " normale" },
            { "sun ", " zon" },
            { "under ", " onder" },
            { "same ", " zelde" },
            { "anyone ", " yian" },
            { "others ", " osse" },
            { "boring ", " boricíon" },
            { "fun ", " bor" },
            { "funny ", " bory" },
            { "murder ", " moord" },
            { "murders ", " moorde" },
            { "bread ", " brood" },
            { "log ", " logag" },
            { "logs ", " logage" },
            { "achievement ", " logro" },
            { "achieve ", " log" },
            { "price ", " precio" },
            { "commit ", " comitó" },
            { "commits ", " comitóe" },
            { "committing ", " comitóa" },
            { "brother ", " bro" },
            { "brothers ", " broe" },
            { "bored ", " boride" },
            { "such ", " sava" },
            { "wall ", " muur" },
            { "eternal ", " eterne" },
            { "january ", " janueer" },
            { "february ", " febueer" },
            { "march ", " mat" },
            { "april ", " april" },
            { "may ", " mis" },
            { "june ", " june" },
            { "july ", " nalim" },
            { "august ", " agost" },
            { "september ", " spokem" },
            { "october ", " spoker" },
            { "november ", " novabo" },
            { "december ", " desember" },
            { "until ", " una" },
            { "operator ", " operatoor" },
        };
    }
}
